### ISSUE TITLE
Running launch via the extension always opens 'Run and Debug' panel

### ISSUE THREAD

**Issue by alexzh2** [ArturoDent/launch-config#5]
Running launch via the extension always opens 'Run and Debug' panel. This behavior is annoying. 
If I run launch without extension, 'Run and Debug' panel opens only if I have breakpoint triggered.

**Comment by ArturoDent** [comment]
Thanks for the issue.  I have removed that behaviour of always opening the Debug View.  It was necessary before because vscode had a bug where the debug toolbar could not be focused without first clicking on the stack trace.  But I believe they fixed that in v1.54.

Please test v0.8.0 - just uploaded - and see if it works as you want.

Thank you.

**Comment by alexzh2** [comment]
Thanks! Now it's work fine!

It still opens 'Debug View' on the very first run after restarting vscode. But without the plugin the same behavior, so I believe that it's not a plugin problem.

**Comment by ArturoDent** [comment]
Closing as fixed in v0.8.0.
